### ISSUE TITLE
TASK-1.3.2 Modify Request a visit form to accomodate  type of user

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#123]
TASK-72.1 Modify Request a visit form to accomodate  type of user

##Task description
- When I get on the page, I want to see the main image of the house I want to do a request for 
- I want to see only the general information of the house (Price, post name, address & construction year)
### As homeowner or renter
- I want a sign in button to submit my form and save it into my account

### As a broker
- I want a sign in button to submit the form and save it into a client's file 
### As homeowner or renter
- I want a sign in button to submit my form and save it into my account

### As a broker
- I want a sign in button to submit the form and save it into a client's file 

- If I click on the main image of the house, I want to be directed to the property page of the house in a new tab
- I want to see information about the person responsible for the home visit so I can contact them if I want

##Acceptance flow

6. User can submit and save into their account with the sign in button
7. If the user is already sign in, they are NOT redirected to the login page and the pop up message confirming the submission appears. 
8. If the user isn't already sign in, they are redirected to the login page

##task breakdown:
- [ ] link back to search result
- [ ] image of house exterior #60 #25 
- [ ] link property page to image of house exterior
- [ ] Info : price #60 #25 
- [ ] Adress #60 #25 
- [ ] Construction year #60 #25 
- [ ] Info of person responsible for house visit #RETRIEVE FROM DATABASE FOR REQUEST #25
- [ ] Your details section textview * editview
- [ ] [BUTTON] Submit: #POPULATE DATABSE FOR REQUEST #25 
- [ ] [BUTTON] Sign in: link to login page
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR HOMEOWNER/RENTER, after log in #POPULATE DATABSE FOR REQUEST #25  
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR BROOKER ....... ?mockup broker 
- [ ] BUTTON] Sign in: Pop up message (Your request was succesfully submit and saved)

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/72#issuecomment-1773949200_

**Comment by DominiqueProulx** [comment]
It was decided during meeting 21-10-2023 that it would be a pop up form , user story was modified to reflect these changes 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/fe98a5a0-6347-4710-8230-e773d8fba2ba)
