### ISSUE TITLE
US - 1.1 Search for a property

### ISSUE THREAD

**Issue by isaisa002** [Broke-Brokers/soen341_fproject2023#124]
Task from #24 

## USER STORY
As I homebuyer or home renter, I want to have a search page with a search bar and result gallery.

### Search bar
1. I want the search bar to contain research criteria for a house:

- Search by city
- House for sale
- House for rent
- Price range
- Number of bedrooms
- Number of bathrooms

***Task Breakdown :
- [x]  [SEARCHBAR] that accepts criteria : city
- [x] [FILTER][CHECKBOXES] For sale / For rent
- [x] [SLIDER] Price range slider
- [x] [SCROLL DOWN] Number of bedrooms
- [x] [SCROLL DOWN] Number of bathrooms

2. I want those main components for the search bar:  

- Search by city
- House for sale
- Prince range 
- Filters box

### Result gallery
1. I want the result gallery to contain 9 house card components. When I click on a house card, I want to be led to the associated property page with all detailed information about the house post.
2. At first, I want to see random house card components in the result gallery. 
After entering a criteria, I want to see the updated result gallery with the house card corresponding to my research with one or more criteria. 

### Search by city
I want the result gallery to be updated with the house card containing the city entered.

### For sale, for rent: type of listing
When I click on the main component “For sale” I want “For rent” to appear. The option is set according to the option I click on. I want “For sale” as the default option. 

### Price
1. When I click on the main component “Price”, I want a container to appear where I can enter the minimum and maximum value of my price range. I want the result gallery to be updated with the house card that falls into my price range
2. When I click on the main component “Filter” I want a container with 2 containers inside: number of bedrooms and number of bathrooms

### Bedroom / bathroom
In the container for the number of bedrooms and bathroom, I want to enter a value. I want the result gallery to be updated with the house card for which the number of bedroom or bathroom is equal to my value

## TASK BREAKDOWN 
issues associated: #24 #25 #26 #27 #28 #29 #30 #31 #32 #46 #55 #59 #60 #61 #69 #96 #97 

- [x]  [SEARCHBAR] that accepts criteria : city
- [x] [FILTER][CHECKBOXES] For sale / For rent
- [x] [SLIDER] Price range slider
- [x] [SCROLL DOWN] Number of bedrooms
- [x] [SCROLL DOWN] Number of bathrooms
- [x] [GRID LAYOUT] shows 9 thumbnails
- [x] [COMPONENT]House card component for thumbnails
- [x] [ALGORTIHM] First gallery results are random 

## USER ACCEPTANCE FLOW

1. On search page #69 #96 , user sees a result gallery with 9 houses card
2. On search page #69  #96 , user set the search with one or more research criteria either by fill the spaces to enter words or values or by selecting the desired with a click.
3. Result gallery update with house card corresponding to inputs from search bar
4. User click on a house card
5. User go on property page #97 
6. User can goes back to search page #69 #96  with click back button

## ACCEPTANCE CRITERIA
issue associated #78 #40 

- Search page has search bar at the top and a result gallery with 9 components 
- Main component of search bar is field: search by city, For sale, Price, Filters
- For sale, Container for price range, container with nb bedrooms & bathrooms appears as drop down when I click on respectively For sale, Price, Filters
- Within container with nb bedrooms & bathrooms
- Information can be entered in fields for search by city and price range
- Clicking on a house card within the result gallery leads to a property page
- Go back button allows to go back to search page
- User acceptance flow is respected
- Documentation present for every new components
- Unit and Ul tests are implemented for every component and function
- There must exist an automated test
- Must match Mockup
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/7f38035e-ad16-4991-aecb-fd03429056a7)

**Comment by DominiqueProulx** [comment]
TASK 1.1.2. Result gallery

### Task description 

As a homebuyer, renter or broker, I want to see thumbnails of the houses in the result gallery so that I can see a preview of the houses that correspond to my search criteria.

### Acceptance flow
1. I want the result gallery to contain 9 house card components. When I click on a house card, I want to be led to the associated property page with all detailed information about the house post.
2. At first, I want to see random house card components in the result gallery. 
After entering a criteria, I want to see the updated result gallery with the house card corresponding to my research with one or more criteria. 
3. (enhancement) I want the result gallery to be updated after I click on the find box. To inform me of that, I want this pop up message: Click on find to see the result of your research

### Acceptance criteria

- [ ] gallery contains 9 house cards components
- [ ] house card compoenent show price, post name, adress number of bedrooms, number of bathroom
- [ ] click on house card component lead to property page
- [ ] results in grid are random on page load
- [ ]  results in grid change with criteria selection 
- [ ]  must match mockup #55 


--- 

### Task Breakdown 

- [x] House card component
- [x] Grid layout
- [x] results in grid are random at first
- [x]  results in grid change with criteria selection

**Comment by taylcr** [comment]
![Image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/31834057/82ddf40c-e52d-4b61-90c7-ac230e69d84f)



![Image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/31834057/242c9959-8e48-4ab7-a48b-d4d99b890c8a)

**Comment by taylcr** [comment]
Added the the filter to the search pages

**Comment by DominiqueProulx** [comment]
Not the best but task breakdown is done @isaisa002

**Comment by DominiqueProulx** [comment]
We need updates on this. We need to discuss what is going on in the issues so that there is visibility and we can all know what is going on. 

Is this done?

**Comment by isaisa002** [comment]
Enhancement is needed. Update doesn't work

**Comment by DominiqueProulx** [comment]
Feature was merged. 

Need to be done : 
Search for City, Neighborhood 
Remove delete button AFTER code was copied for #181 
Link from property to property page needs to be done

**Comment by JPEUMZZ** [comment]
See #277 #278 for updates
