### ISSUE TITLE
TASK-1.1.2. Search Result gallery

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#126]
TASK 1.1.2. Result gallery

### Task description 

As a homebuyer, renter or broker, I want to see thumbnails of the houses in the result gallery so that I can see a preview of the houses that correspond to my search criteria.

### Acceptance flow
1. I want the result gallery to contain 9 house card components. When I click on a house card, I want to be led to the associated property page with all detailed information about the house post.
2. At first, I want to see random house card components in the result gallery. 
After entering a criteria, I want to see the updated result gallery with the house card corresponding to my research with one or more criteria. 
3. (enhancement) I want the result gallery to be updated after I click on the find box. To inform me of that, I want this pop up message: Click on find to see the result of your research

### Acceptance criteria

- [x] gallery contains 9 house cards components
- [x] house card compoenent show price, post name, adress number of bedrooms, number of bathroom
- [x] click on house card component lead to property page
- [x] results in grid are random on page load
- [ ]  results in grid change with criteria selection 
- [ ]  must match mockup #55 

--- 

### Task Breakdown 

- [ ] House card component
- [ ] Grid layout
- [ ] results in grid are random at first
- [ ]  results in grid change with criteria selection

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/124#issuecomment-1774151100_

**Comment by DominiqueProulx** [comment]
For the grid layout ? : https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/searching/

**Comment by DominiqueProulx** [comment]
TASK- 1.1.2.1 House card component 

### Task description 
As a homebuyer, renter or broker, I want to see  a thumbnail of the house so that I can get a preview of the property and see if i'm interested

### Acceptance criteria

- [x]  house card component show price, post name, address number of bedrooms, number of bathroom
- [x] must match mockup

**Comment by DominiqueProulx** [comment]
![277185409-bfd96f8e-ad5a-4225-91f7-a3d0f9757f8f](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/f508fa78-3650-4b3e-9ee2-9422495fd16a)

**Comment by DominiqueProulx** [comment]
- branch was created #search-result-gallery_Taylor-Dominique
- search.js created
- route was created to the search.js
- House_card component created #128  but still needs work to add the save button and request a visit button 
- an instance of house component was added to /search

**Comment by taylcr** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/31834057/ea0da74a-6f9c-4b63-86c1-782c2bb8f580)

**Comment by taylcr** [comment]
I have added the grid in a way to be able to show dynamically the houses listing, and I also added the search link in the nav bar
