### ISSUE TITLE
TASK- 1.1.2.1 House card component

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#128]
task is for #126 

              TASK- 1.1.2.1 House card component 

### Task description 
As a homebuyer, renter or broker, I want to see  a thumbnail of the house so that I can get a preview of the property and see if i'm interested

### Acceptance criteria

- [x]  house card component show price, post name, address number of bedrooms, number of bathroom
- [ ] save to favorite button
- [ ] request a visit button
- [ ] must match mockup #55 

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/126#issuecomment-1774154016_

**Comment by DominiqueProulx** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/bfd96f8e-ad5a-4225-91f7-a3d0f9757f8f)

house component was created. The button for save and visit property need to be modified , I had problem with them.  But component car start being used for grid layout test
