### ISSUE TITLE
US-1.4 Homebuyers Search for brokers

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#131]
### FOR SPRINT2

HIERARCHY 
``` 
     Main page + login  
           Search for Properties
                 property page
           Homebuyers Profile
                 Saved Favorites
      =>   Search for brokers
           Mortage Calculator 
```
### User story Description

As a Homebuyer or Guest, I want to have a search page where I can find a broker so that I can Buy or Sell my house using their services.

### User acceptance flow
1. Home buyer or Guest accesses the website
2. Home buyer or Guest clicks on "Search for a broker" on the navigation bar
6. The page has a gallery with random brokers with a search bar with criteria the user can select : Name, City, Neighbourhood, Years of experience, Broker for renting or buying.
7. When user makes a search for one or many criteria, the brokers cards matching those criteria appear in the gallery.
8. The brokers card contain Name, phone number, years of experience and neighborhood
9. Homebuyer or guest can click on the broker's card thumbnail and it opens a contact form so that the broker can call the client back.
11. a confirmation email is sent to the homebuyer  when a broker has been contacted.

### Acceptance criteria

- [ ] Homebuyer or guest sees the button on navigation bar 
- [ ] must respect mockup
- [ ] User acceptance flow is respected
- [ ] All fields and criteria are available from the brokers database and can be used in the search for brokers page
- [ ] contact form sends an email to the broker
- [ ] homebuyer gets a confirmation email upon sending the broker a contact request
- [ ] Unit test are implemented and run automatically for every component 

---

## TASK BREAKDOWN
TASK - 1.4.1 Mockup for search for brokers page #132
TASK - 1.4.2 Add the search for broker  link to homebuyer and guest navigation bar #133 
TASK - 1.4.3 Create Search-for-Broker.js   page and route from App.js #134 
TASK - 1.4.5 Search-for-brokers page  grid  gallery of brokers #137
TASK - 1.4.6 Search for brokers Search bar and filters #138
TASK - 1.4.7 Add brokers fields to   brokers database #139
TASK - 1.4.8 contact brokers form #140
TASK - 1.4.9 brokers contact email sent + confirmation email to user #141
