### ISSUE TITLE
TASK - 1.4.1 Mockup for search for brokers page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#132]
from : #131 
### TASK DESCRIPTION 

As a development team, I want to follow a mockup of the page so that I can follow the design choices made for the page .

### ACCEPTANCE CRITERIA

- [x] navigation bar #133 
- [ ]look of components #137 #138  #159
- [x] placement of components
- [x] colors and button style
- [x] form style and  field placements #140 #136
- [x] brokers contact email (sent) and confirmation for user received #141

**Comment by DominiqueProulx** [comment]
@isaisa002  I think this is done yes? 
Can you check the criteria, check them, close the issue  and check the task in disucsison #130 if so ? 

Thanks!!

**Comment by isaisa002** [comment]
## SEARCH BROKER PAGE FOR GUEST 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/99e1a983-5fd9-4288-84c4-8143678dcfef)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/878ddd6d-0064-41ab-84e3-5afd345b11ef)


## SEARCH BROKER PAGE FOR ADMIN 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/c56d8b73-05eb-4df8-ac6d-0a9af10d616f)


![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/451678c6-7714-46d0-a15b-f9430893441f)


## SEARCH BROKER PAGE FOR HOME BUYER OR HOME RENTER 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/c0717622-817e-4f9e-970a-19051a33e915)


![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/c8b21e10-c047-463a-8b1b-88e0b26e2f2b)


## BROKER CONTACT FORM FOR HOME BUYER OR HOME RENTER
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/10376af1-cca9-43a1-8bd2-1df5860c32ab)


![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/061ed5bd-b4b2-4143-8175-e0cde2085ea8)
