### ISSUE TITLE
TASK - 1.4.2 Add the search for broker page to homebuyer and guest navigation bar

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#133]
from : #131  and #135

## TASK DESCRIPTION 

As a Homebuyer, Renter or guest I want to to have a "search for broker" button in the top navigation bar  so that I can access the broker search page .

## ACCEPTANCE CRITERIA

- [x] Search for broker button is in top navigation for homebuyers/renters/guests
- [x] must respect mockup #131 
- [x] clicking on the search button brings you to the search page

**Comment by DominiqueProulx** [comment]
Implemented as part of #220  
Merged, unit test done

**Comment by JPEUMZZ** [comment]
@DominiqueProulx this is done no ?

**Comment by DominiqueProulx** [comment]
Yess , we can close
