### ISSUE TITLE
TASK- 1.4.4 Login prompts from search for brokers

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#136]
from : #131 and #135

## TASK DESCRIPTION 

As a homebuyer, renter or guest, I want to be prompt to login  so that I can browser brokers and send email from my account.
- [ ] Login prompt on Search for brokers click  + option to browse as guest
- [ ] Login prompt on broker's thumbnail click if not logged in already
## ACCEPTANCE CRITERIA

- [ ] If user is not logged in when they click on the navigation bar button "Search for brokers", a login form appears
- [ ] Guest have the choice to not log in and "browse as guest"
- [ ] Form has a X in the upper right corner, closing the form with the X has the same effect as "browse as guest"
- [ ] If user is not logged in , clicking on a broker's card to contact them prompts them again to log in , this time there is no choice to send a message as guest : user must be logged in to send an email.

**Comment by DominiqueProulx** [comment]
removed
