### ISSUE TITLE
TASK - 1.4.5 Search-for-brokers page  grid  gallery of brokers 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#137]
from : #131 and #135
TASK - 1.4.5 Search-for-brokers page  grid  gallery of brokers 

## TASK DESCRIPTION 

As a homebuyer,renter or guest, I want to see broker information cards displayed in a gallery so that I can  visualise who I want to contact .

## ACCEPTANCE CRITERIA

- [x] Brokers card appear in a grid
- [x] Brokers card appear random at first
- [x] must follow mockup

**Comment by DominiqueProulx** [comment]
I will start this !

**Comment by DominiqueProulx** [comment]
My branch is older than the merge today. Creating a new branch and will move my component onto it

**Comment by DominiqueProulx** [comment]
## UNIT TEST
Expected : the grid gallery appears with broker's card filled with  brokers information from brokers database
Result : as expected. 


component is working and linked to the firebase. 
I am closing this issue as complete.
The response to criteria will be done from searchbar
