### ISSUE TITLE
TASK - 1.4.6 Search for brokers Search bar and filters

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#138]
from : #131 and #135

## TASK DESCRIPTION 

As a homebuyer, renter or guest, I want to enter search criteria and check filter options so that see the brokers matching my choices in the gallery .

## ACCEPTANCE CRITERIA

- [x] Search bar 
- [x] search criteria that will be matched to brokers database :  Name, Language and Years of experience
- [x] filters the user can select : Years of experience 
- [x] filters can select: language between french & english
- [x] Must follow mockup #132

**Comment by DominiqueProulx** [comment]
After conversation with Isabelle : Adding "language" to Broker 
- needs to be added to broker card
- needs to be added to database

**Comment by DominiqueProulx** [comment]
@JPEUMZZ  Hello! Whats the status here? 

Thanks!

**Comment by JPEUMZZ** [comment]
@DominiqueProulx in progress

**Comment by JPEUMZZ** [comment]
See #279 #222 for updates 
Now we can search a broker by its name

**Comment by isaisa002** [comment]
See #244 #245 for updates 
### Search brokers completed 
### Acceptance criteria respected
- User can search for a broker name, language speak and years of experience
- Search bar is at the top
- Broker result gallery below
- Broker card contains information about broker created in Firebase 
- Broker result gallery updates according to criteria entered
- Search criteria corresponds to database
