### ISSUE TITLE
TASK - 1.4.7 Add brokers fields to   brokers database

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#139]
from : #131  and #135 and #34

## TASK DESCRIPTION 

As development team, I want to add certain fields to the database so that I can fetch them in the search for brokers page .

## ACCEPTANCE CRITERIA

- [x] Add these fields to the brokers database
 - [x]  Years of experience
 - [x] Language
 - [x]  year of experience (can be a range)

**Comment by isaisa002** [comment]
After discussion 3 #130 decided new field would be language speak and years of experience. 
Firebase was set up and populated according to those fields
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/a46ceaaf-778e-4b95-ab88-0c51a58f5018)
