### ISSUE TITLE
TASK - 1.4.8 contact brokers form

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#140]
from : #131 and #135

## TASK DESCRIPTION 

As a Homebuyer, or renter, I want to fill up a form so that a broker receives an email asking to contact me .

## ACCEPTANCE CRITERIA

- [ ] must match mockup #132 
- [ ]  contact form pop up 
- [ ]  information to fill out : Name , last name, phone number, email, renter or buyer(automatic?)
- [ ] button sends an email #141

**Comment by isaisa002** [comment]
## As a team decision
## Contact broker isn't required thus it'll not be implemented anymore
The goal of this form was to connect a broker and a homebuyer or home renter. 
The submit button of the form would create a new client in the client database by saving the user input in the fields of the form. 
This can be done automatically in Firebase.
