### ISSUE TITLE
TASK - 1.4.9 brokers contact email sent + confirmation email to user

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#141]
from : #131 and #135

## TASK DESCRIPTION 

As a homebuyer or renter, I want the form I filled to send an email to the broker so that I can be called back .
As a homebuyer or renter, I want to get a confirmation email so that I know that my contact request has been submitted

## ACCEPTANCE CRITERIA

- [ ] Email is sent with form information when homebuyer or renter click on send in contact form #140 
- [ ] A Confirmation email is received at the email entered in the form #140 
- [ ] must match mockup #132

**Comment by isaisa002** [comment]
This issue is for #140 
Since it is an issue isn't implemented anymore. We don't need to implement task 1.4.9 anymore
