### ISSUE TITLE
US- 3.5 Offer Management

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#142]
## USER STORY DESCRIPTION 
3.5.	Offer Management: Brokers can review and manage offers submitted by homebuyers for properties they represent.

As a broker, I want to send offers on behalf of my clients and track them so that my client can buy a house.
As a broker,  I want to receive and manage offers done on my client's houses. 

## User acceptance flow 
1. The broker logs into his account
2. The broker is redirected to his profile page
3.  the page will appear with those sections:  my profile, property listings.
4. The navigation bar shows :  Broke brokers, search for properties, my profile, clients, offers, disconnect
6. The broker presses on navigation button "offers "
7. Broker's "offer page" hs two main sections : "offers received" and "offers sent".
18.  Broker's "offer page" also has a section with tables with "past sent offers" with status "rejected or accepted"
19.  Broker's "offer page" also has a section with tables with "past  received offers" with status "rejected or accepted"

**Offer received section**
8. Section "offer received"  There is a table with all the offers received and not completed 
9. The broker will have the option to send an email to his selling client about the received offer
10. Clicking on the listing name will open the property page in a separate tab
11.  The broker will have the option  accept or reject an offer, or ask for negotiation.
12. Accepting or rejecting an offer sends an automatic email to client and to the person making an offer
13. "Ask for negociation " will send an automated email asking the seller for a meeting. 

**Offer sent section**
15.  In the "offer sent" section there will be a table with all the offers sent on behalf of his clients, with clients name , price offered and comments and status.
16. A click on the listings name of the sent offers will open the property page in a new tab.

## Acceptance Criteria 

- [ ] must match mockup 
- [ ] User acceptance flow is respected
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Broker-offers.js page is created ins src/Pages/ and the route is created 
- [ ] An unseen offer prompts a  notification icon on the "offer" navigation button : icon is a red circle 
- [ ] The "offer"page :  "offers received" section   : there is a table with all the offers received and not completed :  the information in the table are :  postName of property, the offered price and comments. 
- [ ] "offer" page : "offer received " section : The broker has the option  accept or reject an offer, or ask for negotiation.
 - [ ] Accepting or rejection offer sends an automatic email to the broker and client
 - [ ] Accepting or rejecting updates the other brokers table
 - [ ] Ask for negociation sends the seller asking for a meeting
- [ ] Clicking on any listing property name from the tables in "offer page" open a tab with the property page
 - [ ] There are buttons to accept, reject of negotiate offer 
- [ ] he "offer"page :  The "offers sent" section   : there will be a table with all the offers sent on behalf of his clients, with clients name , price offered and comments and status.
 - [ ]  delete button for offer sent 
 - [ ] There are buttons to delete   
---

## TASK BREAKDOWN

- [ ] TASK - 3.5.1 Mockup   for Offer Management #150
- [ ] TASK - 3.5.3 Create Broker- offers.js   page and route from App.js #152
- [ ] TASK - 3.5.4 Broker-offers page   "offer received" section #153
- [ ] TASK - 3.5.5 Broker-offers page   "offer sent" section #154
- [ ] TASK - 3.5.6 Broker-offers page   "past received" and "past sent" sections #155
- [ ] TASK - 3.5.6 Emails  : email client on offer received +   automatic email after accept or rejet offer or negociation #156
- [ ] TASK - 3.5.7 All database links done for   3.5 #157

**Comment by DominiqueProulx** [comment]
[ ] TASK - 3.5.2  Add new offer notification button ton   navigation bar #151 removed after team discussion. I is removed from backlog.
