### ISSUE TITLE
US- 3.1 Submit Offers

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#143]
## USER STORY DESCRIPTION 
US- 3.1 Submit Offers Brokers can submit offers for buying properties on behalf of their clients, and track the status of their offers.

As a Broker, I want to submit offers on houses for sale so that my client can buy the house if  their offer is accepted.

## User acceptance flow 

1. The broker logs into his account
2. The broker is redirected to his profile page
3.  the page will appear with those sections:  my profile, property listings.
5. The broker presses on navigation button "search for properties"
6. The broker finds the property the client told him they want to buy
7. The broker clicks on the property and lands on the property page
8. The broker clicks on the button "Make an Offer on this hoouse!"
9. We are lead to a make an offer page. 
10. A confirmation email is sent to the client. 
11. The broker's "offers sent" section  is updated with the new offer made.
16.  In the "offer sent" section of the offer page, there is a table with all the offers sent on behalf of all the brokers his clients, with clients name , price offered and comments.
17. A click on the listings name of the sent offers will open the property page in a new tab

## Acceptance Criteria 

- [ ] must match mockup #144 
- [ ] User acceptance flow is respected
- [ ] Unit and UI tests are implemented for every component and function
- [ ] The navigation bar shows :  Broke brokers, search for properties, my profile, clients, offers, disconnect
- [ ] property page has "Make an offer on my house" button
- [ ] "make an offer on my house button " opens a form.
- [ ] The form has fields for : On behalf of Client  X , price offered, comments.
- [ ] The notification icon is a red circle with the number of offers sent in white
- [ ] The "offers received" section  is separated into pending offers, accepted offers and refused offers
- [ ] Pressing "send offer" on form updates the "offer sent" section of the broker 
- [ ] Pressing "send offer" sends a confirmation email to the client on whom's behalf the offer was made
- [ ] Pressing "send offer" sends a confirmation email to the broker

---

## TASK BREAKDOWN

- [ ] TASK - 3.1.1 Mockup for submit offer feature #144
- [ ] TASK - 3.1.2 Brokers navigation Bar  #145
- [ ] TASK - 3.1.3 Make an Offer on this house button in property page #146
- [ ] TASK - 3.1.4 Offer on property form #147
- [ ] TASK - 3.1.5 Make offer on house confirmation emails #148
- [ ] TASK - 3.1.6 Update "offer sent" section of broker "offer" page #149
