### ISSUE TITLE
TASK - 3.1.1 Mockup for Submit offer feature

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#144]
from : #143 

## TASK DESCRIPTION 

As a development team, I want to follow a mockup of the submit offer feature so that I can follow the design choices made.

## ACCEPTANCE CRITERIA

- [x] navigation bar  #145 
- [x] look of components #145 #146  #149 
- [x] placement of components
- [x] colors and button style
- [x] form style and field placements #147
- [x] brokers contact email (sent) and confirmation for offer sent to client #148

**Comment by isaisa002** [comment]
## MAKE AN OFFER PAGE FOR BROKER
### A broker is on the property page, a click on the make an offer button and is lead to a make an offer page that contains a form and information about the house

### The information in the form send an email & set variables in Firebase

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/99eb9b72-dd5a-4ccc-965c-eae41a4d302e)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/fc690aed-84b1-4493-8c40-2fb5ebbe0fe7)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/e1fd38a3-cb90-4e1a-b1e4-c39652c18927)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/565f58e6-8614-4f61-828a-bec9c69194c0)
