### ISSUE TITLE
TASK - 3.1.2 Brokers navigation Bar 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#145]
from : #143 

## TASK DESCRIPTION 

As a broker I want to see the right navigations buttons so I can perform my tasks on the website.

## ACCEPTANCE CRITERIA

- [x] brokers navigation bar has links for "offer"
- [x] brokers navigation bar has links for "my profile"
- [x] brokers navigation bar has links for "clients"
- [ ] brokers navigation bar has links for "mdisconnect"

**Comment by DominiqueProulx** [comment]
i`ll do it!

**Comment by DominiqueProulx** [comment]
## update 

- Implemented as part of #220 
- status : in progress 
>Dependencies : none

### Whaiting on:
-[ ]  @taylcr   disconnect button as par of login
