### ISSUE TITLE
TASK - 3.1.3 Make an Offer on this house button in property page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#146]
from : #143 

## TASK DESCRIPTION 

As a broker I want to click on a button on the property page so that I can make an offer on this property on behalf of my clients

## ACCEPTANCE CRITERIA

- [x] must match mockup #144 
- [x] will link to a form
- [x] appears only for brokers

**Comment by DominiqueProulx** [comment]
UNIT TEST :

Expected:  CLicking on the button leads to /sell page where the "offer form " is 
Result : button behaves as expected
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/08cf4802-c89f-4820-b542-21c282e3a53d)

**Comment by DominiqueProulx** [comment]
Also re- added the link to property page from search page that was removed somewhere.

**Comment by DominiqueProulx** [comment]
## PRE COMMIT TEST
Successful  , i didnt break anything , yay 

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/66e09e66-e5b2-40f9-b657-ff8231505cc4)
