### ISSUE TITLE
TASK - 3.1.4 Offer on property form 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#147]
from : #143 

## TASK DESCRIPTION 

As a broker, I want to fill a form  so that I can make an offer on a house on behalf of my client .

## ACCEPTANCE CRITERIA

- [x] must match mockup #144 
- [x] click on "make an offer on this house" button on property page pops up the form #146 
- [x]  form has fields : On behalf of Client  X , price offered, comments.
- [x] Pressing "send offer" on form updates the "offer sent" section of the broker
- [x] Unit test snapshot done for component

**Comment by DominiqueProulx** [comment]
## SNAPSHOT UNIT TEST 

- snapshot implemented for this component  
- branch :  Offer-form-snapshot_Dominique

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/9b76cbdd-6587-4576-93c4-3e9dcef946b3)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/b526ef82-9b0a-4d0c-bfae-8b35c51c6fe3)

**Comment by JPEUMZZ** [comment]
## Form is created with field from mockup 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/be96d9af-ed8e-4df7-81b8-3bf0b3e179b5)

## Submit button creates a new offer in Firebase according to user input which will updates the offer sent section of the broker
### Client shown in the drop down menu are those from Firebase

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/1613046b-d502-4fda-944a-603111cbc97b)

### In #223, the database will be completely connected with the form meaning  It'll know the broker connected so that in the drop-down menu there is only the client associated with the broker connected

**Comment by JPEUMZZ** [comment]
See #282 for unit test
