### ISSUE TITLE
TASK - 3.1.5 Make offer on house confirmation emails

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#148]
from : #143 

## TASK DESCRIPTION 

As a broker, I want to send a confirmation email to my client once I filled the make an offer on a house form so that my client knows it's been done and what info were in the offer .

### confirmation email for the client 
- [ ] must match mockup
- [ ] Email sent automatically once #147 is sent
- [ ] Confirmation email has all the information in the offer  (price, negociation item, comments)
- [ ]  Confirmation email has a link to the property page

### confirmation email for broker
- [ ] must match mockup
- [ ]  Email sent automatically once #147 is sent
- [ ] Confirmation email has all the information in the offer  (price, negociation item, comments)
- [ ]  Confirmation email has a link to the property page
