### ISSUE TITLE
TASK - 3.5.1 Mockup for Offer Management 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#150]
from : #142

## TASK DESCRIPTION 

As a development team, I want to follow a mockup of the manage offer feature so that I can follow the design choices made\ .

## ACCEPTANCE CRITERIA

- [x] navigation bar   #151
- [x] look of components #152 #154 #154 #155 
- [x] placement of components
- [x] colors and button style
- [x] form style and field placements 
- [x] brokers contact email (sent) and confirmation for offer sent to client  #156

**Comment by isaisa002** [comment]
## OFFER PAGE FOR BROKER
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/835d585e-44c1-48f4-984c-f8e8a12e7025)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/31ba8785-ac2c-4d25-84a5-a4fb8914e180)
