### ISSUE TITLE
TASK - 3.5.4 Broker-offers page "offer received" section

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#153]
from : #141 

## TASK DESCRIPTION 

As a broker I want to see a section of all the offers I received in my offer page so that I accept,reject or negociate the offer.

## ACCEPTANCE CRITERIA

- [x] must respect mockup #150 
- [x] section is component in Brokers-page.js #152 
- [x]   Offer Received section is a table with information : property name , price, comments
 - [x]  next to information are buttons to accept / reject or negotiate offer

**Comment by isaisa002** [comment]
Table created after Firebase crash
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/f47b01a8-afc0-4072-ab48-55b39c726ba1)
