### ISSUE TITLE
TASK - 3.5.5 Broker-offers page "offer sent" section

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#154]
from : #142 

## TASK DESCRIPTION 

As a broker I want to see a section of all the offers I sent in my offer page so that I can keep track of these offers.

## ACCEPTANCE CRITERIA

- [ ] must respect mockup #150 
- [x] section is component in Offer-page.js #152 
- [ ]   Offer Sent section is a table with information : clients name, price offered, status
- [ ] A click on the listing name opens a tab with the property page in another tab

**Comment by RebeccaElusme** [comment]
see update in #280
