### ISSUE TITLE
TASK - 3.5.6 Broker-offers page "past received" and "past sent" sections

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#155]
from : #142

## TASK DESCRIPTION 

As a broker I want to see  sections of all my past received and past sent offers in my offer page so that I can look back on them.

## ACCEPTANCE CRITERIA

- [ ] Past received section : tables with "past received offers" with status "rejected or accepted" #153 
- [ ] Past Sent offers:  tables with sent offers information "past sent offers" with status "rejected or accepted" #154 
- [ ] must match mockup #150

**Comment by isaisa002** [comment]
## As a team decision
### Offer managament would be as this

- A broker can REVIEW the offers he received and the one he sent 
- A broker can MANAGE the offers he received by selectionning the status of the offer he received 
- The offer status will be updated for the broker that received the offer
