### ISSUE TITLE
TASK - 3.5.7 Offer sent and offer received Emails  

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#156]
from : #142 

## TASK DESCRIPTION 

As a broker, I want to send an automatic emails when I accept or reject an offer received so that I can let  the buyer know the clients decision and let my clients know I let the buyer know of the decision

As a broker I want to send an automatic email when my client is asking me to negociate an offer received so that we an arrange a meeting with the other broker

As a broker I want to send an automatic email when my clients offer of a property is retracted so that I can let the seller know my client is no longer interested.

## ACCEPTANCE CRITERIA

- [ ] When clicking on"accept" button "offer received" section of "offer page" #153 an email is sent to my client congratulating them on seling the house
- [ ] When clicking on"accept" button "offer received" section of "offer page" #153 an email is sent to the buyer letting them know my client accepted their offer on the house
- [ ] When clicking on"reject" button "offer received" section of "offer page" #153 an email is sent to my client confirming they are rejecting the buyers offer
- [ ] When clicking on"reject" button "offer received" section of "offer page" #153 an email is sent to the buyer to let them know the brokers client has rejected the offer
- [ ] When clicking on"negociate" button "offer received" section of "offer page" #153 an email is sent to the buyer to let them know the client wants to negociate 
- [ ] When clicking on"retract" button "offer sent" section of "offer page" #153 an email is sent to my client to confirm they are retarcting their offer
- [ ] When clicking on"retract" button "offer sent" section of "offer page" #153 an email is sent to the buyer to let them know the client has retracted it's offer.

**Comment by isaisa002** [comment]
## AS A TEAM DECISION 
### The confirmation will appear in the offer table since the broker will see the updated result
