### ISSUE TITLE
TASK - 1.4.10 Brokers CRUD  on  clients

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#158]
from : #131  , #34 

## TASK DESCRIPTION 

As a broker I want to be able to read, create , edit and delete clients after they contacted me through the search for broker feature so that I can manage my list of clients

## ACCEPTANCE CRITERIA

- [ ] From Brokers client page , a table shows the clients information : name , email, phone , type of client(home byer, renter)
- [ ] A button "add" let's the broker add a client
- [ ] A button "modify" lets the broker modify clients info
- [ ] A button "delete" removes the client from the brokers list

? Should we automate this and not go through email?

**Comment by DominiqueProulx** [comment]
-create a page with list of clients
- add clients to broker in database
-  clients component - in a section  in profile

**Comment by DominiqueProulx** [comment]
@isaisa002  I test created a database. I named it client, I might as well add the fields to it.
Where is the image with all the fields you had created ? I can't find it :S . 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/d05de760-8d95-4276-b459-538d5e85de52)
Thanks

**Comment by isaisa002** [comment]
## As a team decision
### I was decided that CRUD on client wouldn't be implemented 
### This will be automatically by Firebase
It is not required to have a page where a broker can have the option to create, read, update and delete its clients
