### ISSUE TITLE
TASK 1.3.2 - Fields for form request visit

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#173]
from : #72 

## TASK DESCRIPTION 

As a developper, I want to create field so that a user can send a request visit email to a broker

## ACCEPTANCE CRITERIA

form appears when pressing the request a visit button
form has fields:
Name
-Last Name
-Phone Number
-email
-Prefered days
-prefered hour

**Comment by JPEUMZZ** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/a8493677-e1dd-4fe1-9a17-571884f5cb1f)

**Comment by JPEUMZZ** [comment]
TO DO 
- [ ] Prefered date & hours

**Comment by JPEUMZZ** [comment]
Enhancement for sprint 4

- [ ] Prefered dates & time in form
- [ ] Form is formatted for a broker so that we can do US 3.2 - a broker request visit on behalf of a client

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/8a7f9813-7e1d-4b87-868d-fa8c091d555c)
