### ISSUE TITLE
TASK - 0.1 - Home page first page

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#176]
from : #51 

## TASK DESCRIPTION 

As a developper, I want to put a background image, the website's slogan and a button to go on the search 

## ACCEPTANCE CRITERIA

- [x] Page match mock up & branding guide
- [x] The background image needs to be the right size
- [x] The text for the slogan needs to match the branding guide
- [x] Find home button needs to be link to search page

**Comment by JPEUMZZ** [comment]
<img width="1313" alt="image" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/c41de203-8c62-4b6f-a9ab-b8880e3554e6">
