### ISSUE TITLE
TASK 0.2 - Home page You are our priority

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#177]
from : #51 

## TASK DESCRIPTION 

As a developper, I want to create card component that will contain the website objective.

## ACCEPTANCE CRITERIA

- [x] Title match branding guide
- [x] Card contain the image and text from mockup
- [x] Cards should be 8 cm of width and height

**Comment by JPEUMZZ** [comment]
<img width="1265" alt="image" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/a89c158c-4bba-4499-a7c0-864a4e0dc703">
