### ISSUE TITLE
TASK 0.3 - Home page from our user 

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#182]
from : #51 

## TASK DESCRIPTION 

As a developper, I want to create card components so that I can display reviews for our customer.

## ACCEPTANCE CRITERIA

- [x] Title match branding guide
- [x] Card contain image and text from mockup
- [x] Each card should be 8 cm of width and height

**Comment by JPEUMZZ** [comment]
<img width="1221" alt="image" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/bbf550c4-7cdc-43cb-bdf0-acf5a3466ad4">
