### ISSUE TITLE
TASK - 3.3.1 CREATE OPERATION PROPERTY

### ISSUE THREAD

**Issue by RebeccaElusme** [Broke-Brokers/soen341_fproject2023#183]
from : #181 

## TASK DESCRIPTION 
As a broker,
I want to be able to perform CRUD
I want to be able to create a property that will be directly seen on the search page.

## ACCEPTANCE CRITERIA

- [x] Define the database schema for property listings
- [x] Define the fields required for property details and visit requests
- [x] Create tables or entities for property listings : Include fields for property details such as address, type, price
- [x] Add a "Submit" button to the property listing creation form
- [x] Validate form data, ensuring that required fields are filled

**Comment by RebeccaElusme** [comment]
<img width="227" alt="Screenshot 2023-10-26 at 17 21 59" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/117751493/86b1a56b-d263-4324-8ee4-9478188d9cef">

**Comment by RebeccaElusme** [comment]
<img width="414" alt="Screenshot 2023-10-26 at 17 22 39" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/117751493/bebeaac9-ddbb-4f8c-ac27-7ba243368cd6">

**Comment by RebeccaElusme** [comment]
<img width="1342" alt="Screenshot 2023-10-26 at 17 22 57" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/117751493/9da6806d-71da-4dbf-b0b0-0f2821d0562b">

**Comment by DominiqueProulx** [comment]
I added this task to discussion #108  and to broke brokers project
