### ISSUE TITLE
TASK 0.5 - Navigation bar 

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#185]
from : #51 

## TASK DESCRIPTION 

As a developper, I want to create a header that will appears on every page.

## ACCEPTANCE CRITERIA

- [x] LINK Home to home page
- [x] LINK Sell to sell page
- [x] LINK buy to buy page
- [x] LINK Broker to broker page
- [x] LINK Search to search page
- [x] LINK About us to about us page
- [x] LINK Sign to login page
- [x] Make the navigation bar adjustable according to the window size

**Comment by JPEUMZZ** [comment]
<img width="1205" alt="image" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/64c8176d-c692-4cba-a642-84448f16d93e">
<img width="900" alt="image" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/9c0c00f2-8529-41b9-ba4d-26d7211b390e">
