### ISSUE TITLE
TASK - 3.3.4 DELETE PROPERTY

### ISSUE THREAD

**Issue by RebeccaElusme** [Broke-Brokers/soen341_fproject2023#187]
from : #181 

## TASK DESCRIPTION 
As a broker,
I want to be able to perform CRUD
I want to be able to delete the property

## ACCEPTANCE CRITERIA

DELETE:

- [ ] Create a confirmation dialog
- [ ] Implement security measures to ensure that only authorized users
- [ ] Include a "Cancel" button on the confirmation dialog
- [x] backend logic to handle the deletion

**Comment by DominiqueProulx** [comment]
I added this task to discussion #108  and to broke brokers project
