### ISSUE TITLE
MEETINGS NEEDED - End of sprint2 review + Retrospect sprint 2 + Sprint 3 + Sprint 2 planning 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#207]
@Broke-Brokers/broke-brokers 
Okay ! We are 4 days into sprint3 and I am barely getting anything...
As I  said on the discord last week : here are the 3 meetings we need to have :

## SPRINT 2 REVIEW

What is happening with the features? 
#124  , #37 #181  ?? 

I cannot help if you don't ask me and keep me in the dark on where we are at. 
Please advise! we need to go forward!

---

##  SPRINT2 RETROSPECT
What we can learn from sprint 2 : 

### MERGE AS YOU GO! 
without merging as you go : 
- we cannot do integration testing.
- acceptance tests cannot be conducted 
- others cannot learn from your code and use it in another branch to implement something else. that means that development is stalled, and not done in parallel. 
- if somebody else is in charge for unit testing, we cannot do it.
- there is no visibility about progress…. 

let's swarm and destroy ! together! 

### Commenting on issues and giving updates
 The high level issues are created for sprint  3 and they are very organized. please comment on the issues as you go. 
- ask for help!! If you are stuck somewhere , reach out in the comments and ask for help!!  
- update on where you are at on that particular issue
- example : did you start you react app to test to see if the button was working?  That is unit testing, make a comment about it..
- example :  did you create a form but did not finish it ? 2 fields are created? write it in the comments!

Create sub tasks issues if they are needed and comment on these too... 
lets share the knowledge with the rest of the team so we are all owners of the code! 

### Daily Scrum 

A big part of scrum are the daily updates. 
It doesn't matter if you didn't do anything on a particular day! Just say where you are and what you will be working on. 
That way Isabelle can put everything together for the meeting minutes. Also this gives visibility to the team. 
It wont take a lot of time per day and it will make a great difference! :)

---
## SPRINT 3 Plan Meeting 

- [x] Sprint 3 assignments --  let's review them together ! #130 
- [x] Let's go in discussion #130  and make sure that everybody knows what needs to be done. We are all responsible for this!
- [x] Lets go over the design choices together so we all agree and can start on implementing them #130 
- [x] let's agree on task prioritization. #130 

---

Those are my input about these meetings, please prepare some input so we can have a discussion about it and move forward into sprint 3. I was not sure if I needed to make a discussion out of this or an issue. If you want to move it to the discussions, we can definitely do so. 

I propose To 

- [x] set a time for the meeting
- [x] record the discussion and  decisions in the meeting minutes
- [x] record discussion items and decisions in the discussion #130 so we can refer to them as we go. 
- [ ]  Move the daily updates to a discussion on github so there are breadcrumbs of our agile/scrum work there.

**Comment by isaisa002** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/6cc77353-7558-4d82-b6bf-b58efee3d15f)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/59fa2379-51c8-4b7a-9a2d-b609d9576c8b)
