### ISSUE TITLE
TASK - Write Sprint 3 Acceptance tests

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#208]
from : #issueNumber

## TASK DESCRIPTION 

As a development team, I want to write acceptance test so that I can test features that are implemented and consider them done .

## ACCEPTANCE CRITERIA

- [x] 2 acceptance test for 1.4 #131  is written and added to the discussion #130
- [x] 2 acceptance test for #143    is written and added to the discussion #130
- [x] 2 acceptance test for #142     is written and added to the discussion #130
- [x]  Each of the 6 acceptance test are added under the right section in #130 
- [x]  Each of the 6 acceptance tests are added to [ the sprint 3 wiki ](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/wiki/Sprint-3)

**Comment by DominiqueProulx** [comment]
@RebeccaElusme  Would you need a hand with this? I can do it tonight as I will have my hands in this with the sprint 4 backlog?

**Comment by DominiqueProulx** [comment]
@RebeccaElusme  please answer, it's due today and It's worth 2 points in the rubrick.

**Comment by RebeccaElusme** [comment]
Hey @DominiqueProulx  I am doing them now.

**Comment by DominiqueProulx** [comment]
Yea! fire! they are added to the wiki!



![Image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/2e8ccde1-fa71-47b4-a4ca-5831edbb729d)
