### ISSUE TITLE
TASK - 0.5.1 Implement User Registration with Extended Profile Information

### ISSUE THREAD

**Issue by taylcr** [Broke-Brokers/soen341_fproject2023#241]
from: #227 #68 

#### TASK DESCRIPTION

As a developer, I want to implement a user registration feature that not only authenticates users but also captures and stores extended profile information in Firestore, so that we can have a richer user profile for personalized experiences.

#### ACCEPTANCE CRITERIA

- [x] The registration page includes fields for email, password, surname, name, and user type.
- [x] Upon submission, the user's authentication details are stored in Firebase Auth.
- [x] A corresponding user profile document with extended information is created in Firestore's `userProfiles` collection.
- [x] Errors during the registration process are handled and displayed to the user.
- [x] The user is redirected to a welcome page or dashboard after a successful registration.

**Comment by taylcr** [comment]
The switch was necessary for security and simplicity reasons as we talked in the meeting

**Comment by taylcr** [comment]
Done with this part, it worked

**Comment by taylcr** [comment]
I also made a function to keep in track the so say if a user has successfully logged in


  const register = async () => {
        try {
          const userCredential = await createUserWithEmailAndPassword(auth, email, password);
          const additionalInfo = { surname, name, userType };
          await createUserProfile(userCredential, additionalInfo);
          handleLogin(userType); // Call handleLogin with the correct user type
          setSuccess("Successfully signed up! Redirecting to home page...");
          setError("");
          navigateToHome();
        } catch (err) {
          setError(err.message);
          setSuccess("");
        }
      };

**Comment by taylcr** [comment]
The same function above also redirect the user to the main page after login : 

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/31834057/e4a684bf-1263-44fe-a254-d054a10c9930)
