### ISSUE TITLE
US - 1.5 - Mortgage calculator

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#254]
from : #24 
## MORTAGE CALCULATOR

As a Homebuyer , I want to have a mortgage calculator on the property page so that I can calculate what would my monthly payments would be base don the price of the house and the interest .

## User acceptance flow 

1. Home buyer  accesses the website
2. Home buyer  on "Search for a property" on the navigation bar
6. The home buyer accesses a property page through the results of the search for property page
7. If the property is of type "Buy", the monrtgage calculator component appears on the page
8. The homebuyer enters the down payment, the interest rate, the loan term
9. The house price and taxes are already in the calculator
10. Clicking "calculate monthly payment" calculates the payment and it's showns clearly at the bottom of the card
.

HIERARCHY 
``` 
     Main page + login  
           Search for Properties
                 property page
                   => mortgage calculator
           Search for brokers
           Homebuyers Profile
                 Saved Favorites
           
```
## Acceptance Criteria 

- [ ] Dedicated mortgage calculator tool accessible from the property page
- [ ]  Mortgage calculator appears only on property that are to buy (not to rent)
- [ ]  The house price appears automatically in the calculator 
- [ ]  The user can enter interest rate
- [x] The user can enter loan term (in years),
- [ ] The property tax rate is applied and appears automatically in the calculator 
- [x] The user can enter down payment
- [ ] The load amount is calculated automatically
- [x] The calculator display the estimated monthly mortgage payment
- [ ] The user has option to adjust the input values and recalculate the estimated monthly payment as much as needed
- [ ] Must match mockup
- [ ] A unit test Snapshot must be done for the component 

---

## TASK BREAKDOWN

- [ ] #263
- [x] #264
- [ ] #265
- [x] #266
- [x] #267
- [x] #268
- [x] #269

**Comment by DominiqueProulx** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/c3380776-9243-4e5d-bc07-6a9bd6469390)

**Comment by DominiqueProulx** [comment]
@RebeccaElusme  do you have any comments since you worked on the mortage calculator?
