### ISSUE TITLE
TASK - 1.5.1 Mockup for Mortgage calculator

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#263]
from : #245
## TASK DESCRIPTION

As a development   team, I want to follow a mockup of the mortgage calculator so that I can   follow the design choices made .

## ACCEPTANCE CRITERIA 
- [ ] look of components  #245
- [ ] placement of components
- [ ] colors and button style
- [ ] form style and field placements #266
