### ISSUE TITLE
TASK 1.5.2 Property page linked to database

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#264]
from : #254
## TASK DESCRIPTION

As a development team, I want the property page to be linked to the database to I can use the information of a specific home in the mortage calculator

## ACCEPTANCE CRITERIA 
- [ ]  All the fields of the property are updated based on property ID linked to the page
- [ ]  If no property ID is linked to the page , the page must display Dummy variables
- [ ]  The ID is provided by the search page
