### ISSUE TITLE
TASK - 1.5.4 Mortgage calculator fields

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#266]
from : #254
## TASK DESCRIPTION

As a Homebuyer, I want to fill a form  so that I can see the monthly payments I would have to make on a property

## ACCEPTANCE CRITERIA 
- [ ]  The house price appears automatically in the calculator
- [ ]   The user can enter interest rate
- [ ]   The user can enter loan term (in years),
- [ ]   The property tax rate is applied and appears automatically in the calculator
- [ ]  The user can enter down payment
- [ ]   The load amount is calculated automatically
- [ ]   The user has option to adjust the input values and recalculate the estimated monthly payment as much as needed
- [ ]  Must match mockup
- [ ]  A unit test Snapshot must be done for the component

**Comment by DominiqueProulx** [comment]
Form started to create the component 
see https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/268#issuecomment-1813887069 

additions have been merged, you can pit it up from there 

```
{/*the mortgage calculator form*/}
    <form >
    <div className='inputs'>
     <div className='input'>       
      <input type="" placeholder='an input' value="aValue" /> 
        </div>
         </div>

        <button type="button"  className="calculate" onClick={calculateMortgage} > Calculate</button>
</form>


<div><p>Your monthly payment : {monthlyPayment} $</p></div>
</div>
```
