### ISSUE TITLE
TASK - 1.5.6 Add Mortgage calculator to property page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#268]
from : #254
depends on : #263 #266 #267
## TASK DESCRIPTION

As a homebuyer, I want to see the mortgage calculator on properties that are to buy so that I can calculate my monthly payment 

## ACCEPTANCE CRITERIA 
- [ ]  Must match mockup
- [ ]  A unit test Snapshot must be done for the component
- [ ]   Dedicated mortgage calculator tool accessible from the property page
- [ ]  Mortgage calculator appears only on property that are to buy (not to rent)

**Comment by DominiqueProulx** [comment]
working in branch : mortageCalculator-component_Dominique

- The mortgage calculator component is added to the property page. 
-  Css for the mortgage calculator created and css for the container and button added
- Function calculateMortgage has been created but does not do anything for now
- Button has been created and calls the function on click

merging these first additions


![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/06e0aed0-2800-4e61-8afd-3e8cb1dcd01a)
