### ISSUE TITLE
TASK - 1.6.1 Mockup for distance to interest calculator

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#270]
from : #16
## TASK DESCRIPTION

As a development team, I want to follow a mockup of the distance to interest calculator sectionsso that I can follow the design choices made .

## ACCEPTANCE CRITERIA 
- [ ] look of components  #274 #272 #273
- [ ] placement of components 
- [ ] colors and button style
