### ISSUE TITLE
TASK - 1.6.2 Interest database created with InterestNb, interestName,HomebuyerID, Latitude and Longitude fields

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#271]
from : #16
## TASK DESCRIPTION

As a development team, I want the five interest fields added to the interest database so that I can use them in the distance to interest calculator

## ACCEPTANCE CRITERIA 
- [ ]  HomebuyerID 
- [ ] InterestNB 
- [ ] Interest1Name , latitude, longitude
- [ ] Interest2Name , latitude, longitude
- [ ] Interest3Name , latitude, longitude
- [ ] Interest4Name , latitude, longitude
- [ ] Interest5Name , latitude, longitude
