### ISSUE TITLE
TASK - 1.6.6  FORM to change my interests in profile page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#272]
from : #16
## TASK DESCRIPTION

As a homebuyer, I want to be able to change or add my five location of interest so that they can be used in the distance to interest calculator on the property page

## ACCEPTANCE CRITERIA 
- [ ]  Form has scroll down with number 1 to 5 to chose the interest to change
- [ ] Form has a field : Name of Interest
- [ ] Form has a field for "address"
- [ ]  Form has a field for "City"
- [ ] Form has a field for "Postal code"
- [ ] Submit calls ChangeAdressToLatLong function #294 
- [ ] Submit stores the field info and the return of ChangeAdressToLatLong to the interest database #293
