### ISSUE TITLE
TASK - 1.6.3 My interest section in Homebuyer profile page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#274]
## TASK DESCRIPTION

As a homebuyer I want to have a "my interest" section in my profile so that I can add my five location of interest 

## ACCEPTANCE CRITERIA

- [ ]  Profile section  "MyInterests"  is added to Profile page. 
- [ ] It's a component created that has a table that displays the interest 1 to 5 of HomebuyerID 1 to 5
- [ ] The component also contain the form to update the interests #272 
- [ ] Must match mockup
- [ ]  Snapshot Unit test must be done pre-commit and test must be merged into main
