### ISSUE TITLE
TASK - 1.6.8 Snapshot tests done for profile page interest section

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#275]
from : #16
Depends on : #274 #293 
## TASK DESCRIPTION

As a   development team I want to make a snapshot of the new component so that I can   perform pre commit unit tests against that snapshot

## ACCEPTANCE CRITERIA 
- [ ]  Snapshot test file created
- [ ]  Snapshot ran sucessfully
- [ ] Merged into main with the component
