### ISSUE TITLE
TASK - 1.6.7 Snapshot tests done for property page distance to interest section

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#276]
from : #16
Depends on : #273 
## TASK DESCRIPTION

As a development team I want to make a snapshot of the new component so that I can perform pre commit unit tests against that snapshot

## ACCEPTANCE CRITERIA 
- [ ]  Test file created
- [ ]  test ran sucessfully
- [ ]  merged with component
