### ISSUE TITLE
TASK 1.1.4 - Search criteria for properties

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#277]
from : #124 

## TASK DESCRIPTION 

As a developper, I want to write functions that communicate with Firebase and return properties found in the collection "Property" equals to user input so that a guest, broker, home buyer/renter

## TASK BREAKDOWN
- [x] Search by city: result gallery is updated with the house card containing the city entered
- [x] In a drop down menu, a click on For sale/For rent, the result gallery is updated with the properties that the listing type is For sale/For rent
- [x] The option is set according to the option I click on
- [x] Price: When I click on the main component “Price”, I want a container to appear where I can enter the minimum and maximum value of my price range. 
- [x] According to range selected, I want the result gallery to be updated with the house card that falls into my price range
- [x] When I click on the main component “Filter” I want a container with 3 containers inside: number of bedrooms and number of bathrooms.
- [x] In the container for the number of bedrooms and bathroom, I want to enter a value. I want the result gallery to be updated with the house card for which the number of bedroom or bathroom is equal to my value

## ACCEPTANCE CRITERIA
- Search page has search bar at the top and a result gallery with 9 components 
- Main component of search bar is field: search by city, For sale, Price, Filters
- For sale, Container for price range, container with nb bedrooms & bathrooms appears as drop down when I click on respectively For sale, Price, Filters
- Within container with nb bedrooms & bathrooms
- Information can be entered in fields for search by city and price range

**Comment by JPEUMZZ** [comment]
## Heres the user input field for city and the drop down menu for type of listing
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/206deaf9-912b-476e-8d31-0da6b21f67df)

## Search by city
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/b5e82ef6-ea98-4560-99be-ac963d05e949)

## Search according to type of listing
The function research in Firebase all properties with a type of listing that have "sale" or "rent" in it
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/46aa656a-07a0-4c33-b987-547c75a1f985)

## Search by price selected with a range slider
The range component sets value
The function reads value from the range component and return properties within that the price are within those values

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/73ed08db-7640-47f0-8bbb-e9f7ea7e70d4)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/e5d052b0-2ef2-4bf7-b743-ffa376a2aa04)

## Search by number of bedrooms or bathrooms
The filter function returns properties in Firebase that corresponds to the variables bedrooms & bathrooms
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/4f2818d6-2b24-4c22-b4b1-66c209758560)

Those values are set according to user input
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/98b28fdc-1f05-45b0-91bb-8fe9870c5ced)

**Comment by JPEUMZZ** [comment]
UI NEEDS ENHANCEMENT
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/139810334/237b2a7a-1ee2-459c-b4cf-12fa0e09d229)
