### ISSUE TITLE
TASK - 1.6.4 My interest table 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#293]
from : #16 
dependent on : #270 #271 #274 

## TASK DESCRIPTION 

As a homebuyer I want to see a table displaying my 5 interests so that I can make sure these are the interests I want the distance to interest calculator to use.

## ACCEPTANCE CRITERIA

- [ ]  Interests 1 to 5 are displayed
- [ ] Interests 1 to 5 are fetched from the myInterest database
- [ ] column interest number 
- [ ] column: Name 
- [ ] column : Address 
- [ ] Must match mockup
- [ ] Unit test snapshot is done for every new components
- [ ]  Unit tests runs successfully on pre-commit tests
