### ISSUE TITLE
TASK  - 1.6.5 ChangeAdressToLatLong function

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#294]
from : #16
depends on : #272 

## TASK DESCRIPTION 

As a development team I want a function that takes the input address and changes it to a set of latidude and longitude so that I can store them as such in the interest database.

https://developers.google.com/maps/documentation/geocoding/overview

## ACCEPTANCE CRITERIA

- [ ] function is attached to change my interest form
- [ ]  function uses Ggoogle Geocoding to change the adress from the form to a set of latidude and longitude
- [ ] function returns the set of longitude and latitude 
- [ ] Unit test snapshot is done for every new components
- [ ]  Unit tests runs successfully on pre-commit tests
