### ISSUE TITLE
TASK 0.4 - Footer

### ISSUE THREAD

**Issue by JPEUMZZ** [Broke-Brokers/soen341_fproject2023#95]
from : #51 

## TASK DESCRIPTION 

As a developper, I want to create a footer with information about how to contact us

## ACCEPTANCE CRITERIA

- [x] HTML structure for the footer with the necessary HTML tags and elements to define the content within the footer section.
- [x] Styling with CSS according to mockup
- [ ] Functionality and Interactivity: Button for Instagram leads to an Instagram page
- [ ] Functionality and Interactivity: Button for Twitter leads to an twitter page
- [ ] Functionality and Interactivity: Button for facebook leads to an facebook page
- [ ] Functionality and Interactivity: Button for linkedin leads to an linkedin page

**Comment by isaisa002** [comment]
![Image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/3e46d9a1-55a7-48b4-9719-d602a1dc9049)
